// OAuthUtils ----------------------------------------------------------------

// General utilities for the OAuth Orchestrator implementation.

// External Modules ----------------------------------------------------------

const bcrypt = require("bcrypt");
import crypto from "crypto";
import util from "util";

// Internal Modules ----------------------------------------------------------

//const promisifiedPbkdf2 = util.promisify(crypto.pbkdf2);
const promisifiedRandomBytes = util.promisify(crypto.randomBytes);

// Private Objects -----------------------------------------------------------

/*
const HASH_ALGO:string = "sha512";      // Algorithm to be used
const HASH_BYTES = 64;                  // Match algorithm length / bits (512 / 8)
const HASH_ITERATIONS: number = 100000; // NIST recommends 10000, so 10x
const HASH_SALT_BYTES: number = 16;     // Exceed NIST minimum 4 (32/8)

const atob = (input: string) =>
    Buffer.from(input, "base64");
const btoa = (input: any) =>
    input.toString("base64").replace(/\=+$/, '');
const normalize = (str: string) =>
    Buffer.from(String(str).normalize("NFKC"));
*/

// Public Objects ------------------------------------------------------------

/**
 * Generate and return a random token, with an optional specified length
 * in bytes, converted to hex encoding.
 *
 * @param desiredSize Desired number of bytes (hex will be this * 4 in length)
 */
export const generateRandomToken
    = async (desiredSize: number = 32): Promise<string> =>
{
    const buffer: Buffer = await promisifiedRandomBytes(desiredSize);
    return buffer.toString("hex");
}

/**
 * Perform a one-way hash on the specified password, and return the result
 * as a string.
 *
 * @param password      Plain-text password to be hashed
 */
export const hashPassword
    = async (password: string): Promise<string> =>
{
    const SALT_ROUNDS: number = 10;
    return await bcrypt.hash(password, SALT_ROUNDS);
}

/**
 * Verify that the specified plain-text password hashes to the specified
 * hash value.
 *
 * @param password      Plain-text password to be checked
 * @param hash          Hashed password previously calculated by hashPassword()
 */
export const verifyPassword
    = async (password: string, hash: string): Promise<boolean> =>
{
    return bcrypt.compare(password, hash);
}

/*
// hashPassword() and verifyPassword() are based on the example found at:
// https://gist.github.com/tracker1/87bbebbf235e697588fc9d9b8ca4f0a2

/!**
 * Perform a one-way hash on the specified password, and return the result
 * as a string.  The salt that was used will be embedded.
 *
 * @param password      Plain-text password to be hashed
 *!/
export const hashPassword
    = async (password: string): Promise<string> =>
{
    const salt = await promisifiedRandomBytes(HASH_SALT_BYTES);
    const result = await promisifiedPbkdf2(
        normalize(password),
        salt,
        HASH_ITERATIONS,
        HASH_BYTES,
        HASH_ALGO
    );
    return `${btoa(salt)}.${btoa(result)}`;
}

/!**
 * Verify that the specified password matches the specified hashed password
 * that was previously generated by hashPassword().
 *
 * @param password      Plain-text password to be verified
 * @param hash          Previously calculated hash calculated by hashPassword()
 *!/
export const verifyPassword
    = async (password: string, hash: string): Promise<boolean> =>
{
    if (hash.length > 120) {
        return false; // hash is impossibly long
    }
    const [salt, result] = hash.split(".");
    console.info(`Split values are ${salt} and ${result}`);
    const result2 = await promisifiedPbkdf2(
        normalize(password),
        atob(salt),
        HASH_ITERATIONS,
        HASH_BYTES,
        HASH_ALGO
    );
    return result === btoa(result2);

}
*/
