# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Ubuntu Smoke Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  UbuntuSmokeTest:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      ACCESS_LOG: stdout
      CLIENT_LOG: stdout
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
      OAUTH_ENABLED: true
      PORT: 8080
      SERVER_LOG: stdout
      SUPERUSER_SCOPE: superuser

    steps:
      - uses: actions/checkout@v3
      - name: Ubuntu With Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run dbpush
      - run: npm run build
      - run: npm run test:ci
